/* Auto-generated by genmsg_cpp for file /home/alaina/ros/ros_affective/msg/disposition.msg */
#ifndef ROS_AFFECTIVE_MESSAGE_DISPOSITION_H
#define ROS_AFFECTIVE_MESSAGE_DISPOSITION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace ros_affective
{
template <class ContainerAllocator>
struct disposition_ {
  typedef disposition_<ContainerAllocator> Type;

  disposition_()
  : disposition()
  {
  }

  disposition_(const ContainerAllocator& _alloc)
  : disposition(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _disposition_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  disposition;


private:
  static const char* __s_getDataType_() { return "ros_affective/disposition"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "e4e96729864144af60964d26bfde8a66"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "string disposition\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, disposition);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, disposition);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(disposition);
    return size;
  }

  typedef boost::shared_ptr< ::ros_affective::disposition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_affective::disposition_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct disposition
typedef  ::ros_affective::disposition_<std::allocator<void> > disposition;

typedef boost::shared_ptr< ::ros_affective::disposition> dispositionPtr;
typedef boost::shared_ptr< ::ros_affective::disposition const> dispositionConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ros_affective::disposition_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ros_affective::disposition_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ros_affective

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ros_affective::disposition_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ros_affective::disposition_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ros_affective::disposition_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e4e96729864144af60964d26bfde8a66";
  }

  static const char* value(const  ::ros_affective::disposition_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe4e96729864144afULL;
  static const uint64_t static_value2 = 0x60964d26bfde8a66ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_affective::disposition_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ros_affective/disposition";
  }

  static const char* value(const  ::ros_affective::disposition_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ros_affective::disposition_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string disposition\n\
";
  }

  static const char* value(const  ::ros_affective::disposition_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ros_affective::disposition_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.disposition);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct disposition_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_affective::disposition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ros_affective::disposition_<ContainerAllocator> & v) 
  {
    s << indent << "disposition: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.disposition);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROS_AFFECTIVE_MESSAGE_DISPOSITION_H

