/* Auto-generated by genmsg_cpp for file /home/alaina/ros_affective/msg/expression.msg */
#ifndef ROS_AFFECTIVE_MESSAGE_EXPRESSION_H
#define ROS_AFFECTIVE_MESSAGE_EXPRESSION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace ros_affective
{
template <class ContainerAllocator>
struct expression_ {
  typedef expression_<ContainerAllocator> Type;

  expression_()
  : linear(0)
  , angular(0)
  {
  }

  expression_(const ContainerAllocator& _alloc)
  : linear(0)
  , angular(0)
  {
  }

  typedef uint64_t _linear_type;
  uint64_t linear;

  typedef uint64_t _angular_type;
  uint64_t angular;


private:
  static const char* __s_getDataType_() { return "ros_affective/expression"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "fb40fee2d116c89f4167ac7300b53c4b"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "uint64 linear\n\
uint64 angular\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, linear);
    ros::serialization::serialize(stream, angular);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, linear);
    ros::serialization::deserialize(stream, angular);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(linear);
    size += ros::serialization::serializationLength(angular);
    return size;
  }

  typedef boost::shared_ptr< ::ros_affective::expression_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_affective::expression_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct expression
typedef  ::ros_affective::expression_<std::allocator<void> > expression;

typedef boost::shared_ptr< ::ros_affective::expression> expressionPtr;
typedef boost::shared_ptr< ::ros_affective::expression const> expressionConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ros_affective::expression_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ros_affective::expression_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ros_affective

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ros_affective::expression_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ros_affective::expression_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ros_affective::expression_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fb40fee2d116c89f4167ac7300b53c4b";
  }

  static const char* value(const  ::ros_affective::expression_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xfb40fee2d116c89fULL;
  static const uint64_t static_value2 = 0x4167ac7300b53c4bULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_affective::expression_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ros_affective/expression";
  }

  static const char* value(const  ::ros_affective::expression_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ros_affective::expression_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint64 linear\n\
uint64 angular\n\
\n\
";
  }

  static const char* value(const  ::ros_affective::expression_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ros_affective::expression_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ros_affective::expression_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.linear);
    stream.next(m.angular);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct expression_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_affective::expression_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ros_affective::expression_<ContainerAllocator> & v) 
  {
    s << indent << "linear: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.linear);
    s << indent << "angular: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.angular);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROS_AFFECTIVE_MESSAGE_EXPRESSION_H

