/* Auto-generated by genmsg_cpp for file /home/alaina/ros/ros_affective/msg/personality.msg */
#ifndef ROS_AFFECTIVE_MESSAGE_PERSONALITY_H
#define ROS_AFFECTIVE_MESSAGE_PERSONALITY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace ros_affective
{
template <class ContainerAllocator>
struct personality_ {
  typedef personality_<ContainerAllocator> Type;

  personality_()
  : intravert_extravert(0.0)
  , intuitive_sensing(0.0)
  , thinking_feeling(0.0)
  , judging_perceiving(0.0)
  {
  }

  personality_(const ContainerAllocator& _alloc)
  : intravert_extravert(0.0)
  , intuitive_sensing(0.0)
  , thinking_feeling(0.0)
  , judging_perceiving(0.0)
  {
  }

  typedef float _intravert_extravert_type;
  float intravert_extravert;

  typedef float _intuitive_sensing_type;
  float intuitive_sensing;

  typedef float _thinking_feeling_type;
  float thinking_feeling;

  typedef float _judging_perceiving_type;
  float judging_perceiving;


private:
  static const char* __s_getDataType_() { return "ros_affective/personality"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "3f04b92cb10637c204665cb28a6d5710"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float32 intravert_extravert\n\
float32 intuitive_sensing\n\
float32 thinking_feeling\n\
float32 judging_perceiving\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, intravert_extravert);
    ros::serialization::serialize(stream, intuitive_sensing);
    ros::serialization::serialize(stream, thinking_feeling);
    ros::serialization::serialize(stream, judging_perceiving);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, intravert_extravert);
    ros::serialization::deserialize(stream, intuitive_sensing);
    ros::serialization::deserialize(stream, thinking_feeling);
    ros::serialization::deserialize(stream, judging_perceiving);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(intravert_extravert);
    size += ros::serialization::serializationLength(intuitive_sensing);
    size += ros::serialization::serializationLength(thinking_feeling);
    size += ros::serialization::serializationLength(judging_perceiving);
    return size;
  }

  typedef boost::shared_ptr< ::ros_affective::personality_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_affective::personality_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct personality
typedef  ::ros_affective::personality_<std::allocator<void> > personality;

typedef boost::shared_ptr< ::ros_affective::personality> personalityPtr;
typedef boost::shared_ptr< ::ros_affective::personality const> personalityConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ros_affective::personality_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ros_affective::personality_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ros_affective

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ros_affective::personality_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ros_affective::personality_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ros_affective::personality_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3f04b92cb10637c204665cb28a6d5710";
  }

  static const char* value(const  ::ros_affective::personality_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3f04b92cb10637c2ULL;
  static const uint64_t static_value2 = 0x04665cb28a6d5710ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_affective::personality_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ros_affective/personality";
  }

  static const char* value(const  ::ros_affective::personality_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ros_affective::personality_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 intravert_extravert\n\
float32 intuitive_sensing\n\
float32 thinking_feeling\n\
float32 judging_perceiving\n\
";
  }

  static const char* value(const  ::ros_affective::personality_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ros_affective::personality_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ros_affective::personality_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.intravert_extravert);
    stream.next(m.intuitive_sensing);
    stream.next(m.thinking_feeling);
    stream.next(m.judging_perceiving);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct personality_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_affective::personality_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ros_affective::personality_<ContainerAllocator> & v) 
  {
    s << indent << "intravert_extravert: ";
    Printer<float>::stream(s, indent + "  ", v.intravert_extravert);
    s << indent << "intuitive_sensing: ";
    Printer<float>::stream(s, indent + "  ", v.intuitive_sensing);
    s << indent << "thinking_feeling: ";
    Printer<float>::stream(s, indent + "  ", v.thinking_feeling);
    s << indent << "judging_perceiving: ";
    Printer<float>::stream(s, indent + "  ", v.judging_perceiving);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROS_AFFECTIVE_MESSAGE_PERSONALITY_H

