(cl:in-package ros_affective-msg)
(cl:export '(ACCEPTANCE-VAL
          ACCEPTANCE
          CURIOSITY-VAL
          CURIOSITY
          EATING-VAL
          EATING
          FAMILY-VAL
          FAMILY
          HONOR-VAL
          HONOR
          IDEALISM-VAL
          IDEALISM
          INDEPENDENCE-VAL
          INDEPENDENCE
          ORDER-VAL
          ORDER
          PHYSICAL_ACTIVITY-VAL
          PHYSICAL_ACTIVITY
          POWER-VAL
          POWER
          ROMANCE-VAL
          ROMANCE
          SAVING-VAL
          SAVING
          SOCIAL_CONTRACT-VAL
          SOCIAL_CONTRACT
          STATUS-VAL
          STATUS
          TRANQUILITY-VAL
          TRANQUILITY
          VENGEANCE-VAL
          VENGEANCE
))